= Monitoring Tekton Tasks and Pipelines with Elastic Observability
:imagesdir: ./images

In a few minutes, you will have the following components up and running in your local Kubernetes cluster:

* Tekton https://github.com/tektoncd/pipeline/releases/tag/v0.18.1[**v0.18.1**] in the `tekton-pipelines` namespace
* Elastic Stack **7.10.0**, Elasticsearch / Kibana / Beats (filebeat and metricbeat) deployed using https://github.com/elastic/cloud-on-k8s[Elastic Cloud on Kubernetes (ECK)] in the `elastic-system` namespace


== Prerequisites

* Kubernetes environment (Docker for Desktop, Minikube, GKE...) 

== Helpers

If you don't want to follow all the tutorial step by step, you can use the helpers scripts, *make sure to be connected to your dev environment*
[source,shell]
--
# Install Tekton Pipelines / ECK / Elasticsearch / Kibana / Beats
$ ./helpers/set-up-env.sh
--

To add some data by executing some Tasks and Pipelines, run the following:
[source,shell]
--
# Install some Tekton Tasks and Pipelines official examples
$ ./helpers/add-data.sh 0.18.1 default
--

The dashboard used in the demo is available at ./helpers/tekton-dashboard.ndjson

Use the script below to clean up your environment
[source,shell]
--
# Install some Tekton Tasks and Pipelines official examples
$ ./helpers/clean-all.sh
--

== Set up Tekton Pipelines and CLI

.Install Tekton Pipelines CRD
[source,shell]
--
# make sure you are using the right k8s context
$ kubectl config current-context
docker-for-desktop

# install Tekton Pipelines
$ kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.18.1/release.yaml

# Wait until all Tekton pods are ready
$ kubectl get pods -w -n tekton-pipelines
NAME                                           READY   STATUS    RESTARTS   AGE
tekton-pipelines-controller-77f74f5bcf-rbj8s   1/1     Running   0          1m
tekton-pipelines-webhook-f76c97965-5xkxq       1/1     Running   0          1m
--

.Set up Tekton CLI

Find the best way to install it based on your local system by loogin at the official documentation:

.Homebrew example
[source,shell]
--
brew install tektoncd-cli
--

.Check the versions
[source,shell]
--
$ tkn version
Client version: 0.14.0
Pipeline version: v0.18.1
--

== Get your first Tekton Task running!

.Install Tekton Task from the catalog
```bash
# Install git clone Task from Tekton 
$ tkn hub get task git-clone --version 0.2 |  kubectl apply -f -
task.tekton.dev/git-clone created
```

.Execute a Task and check logs
```bash
# Create a PVC to share data between tasks
$ cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-source
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
EOF
persistentvolumeclaim/go-source created

# Execute the Task to clone the repo
$ cat <<EOF | kubectl apply -f -
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: clone-my-code
spec:
  taskRef:
    name: git-clone
  workspaces:
  - name: output
    persistentVolumeClaim:
      claimName: go-source
  params:
  - name: url
    value: https://github.com/elastic/go-licenser.git
  - name: revision
    value: master
EOF
taskrun.tekton.dev/clone-my-code created
```

.Check the result and logs
```bash
$ tkn tasktuns list
NAME            STARTED          DURATION     STATUS
clone-my-code   25 seconds ago   16 seconds   Succeeded

$ tkn taskruns logs clone-my-code -f
...
[clone] + /ko-app/git-init -url https://github.com/elastic/go-licenser.git -revision v0.3.1 -refspec  -path /workspace/output/ '-sslVerify=true' '-submodules=true' -depth 1
[clone] {"level":"info","ts":1607989263.4070501,"caller":"git/git.go:165","msg":"Successfully cloned https://github.com/elastic/go-licenser.git @ 857b4969bc2f753ffb9eb3a885d01a59a9f22cdb (grafted, HEAD) in path /workspace/output/"}
[clone]
...

```

Let's see how to use Elastic Observability to monitor any Tekton Tasks and Pipelines.

== Set up Elastic Observability with Elastic Cloud on Kubernetes (ECK)

.Install ECK
[source,shell]
--
$ kubectl apply -f https://download.elastic.co/downloads/eck/1.3.1/all-in-one.yaml
--

.Deploy Elasticsearch, Kibana and Beats
[source,shell]
--
$ kubectl apply -n elastic-system -f https://raw.githubusercontent.com/mgreau/tekton-pipelines-elastic-tutorials/master/config/eck/monitoring-es-kb.yaml

$ kubectl apply -n elastic-system -f https://raw.githubusercontent.com/mgreau/tekton-pipelines-elastic-tutorials/master/config/eck/monitoring-filebeat-metricbeat.yaml
--

When the set-up is done, you should have a *all the Elastic components up and running in the elasic-system* namespace:

[source,shell]
--
# Check Elastic pods
$ kubectl get pods -n elastic-system
NAME                                    READY   STATUS    RESTARTS   AGE
elastic-operator-0                      1/1     Running   1          5m
elasticsearch-monitoring-es-default-0   1/1     Running   1          5m
filebeat-beat-filebeat-b6vlt            1/1     Running   7          5m
kibana-monitoring-kb-599698987-7cjqq    1/1     Running   1          5m
metricbeat-beat-metricbeat-fsz5p        1/1     Running   7          5m
--

.Get the `elastic` user password needed to access the UI
[source,shell]
--
$ echo $(kubectl get secret -n elastic-system elasticsearch-monitoring-es-elastic-user -o=jsonpath='{.data.elastic}' | base64 --decode)
XXXXXXXXXXXXXX
--

.Make Elastic Kibana available
[source,shell]
--
$ kubectl port-forward -n elastic-system svc/kibana-monitoring-kb-http 5601
--

Then you can access the following URL and use the credentials from above:

- https://localhost:5601/app/observability/overview

_Note: the intent of this tutorial is to provide a development environment. To install a valide certificate, please refer to the official Elastic documentation._


== Monitor Build using Elastic Observability

Everything is ready to monitor Tasks and Pipelines.

.Install Tekton Tasks from the Catalog to build and test a golang project
[source,shell]
--
# Install golang build and test Tasks from the catalog
$ tkn hub get task golang-test --version 0.1 |  kubectl apply -f -
task.tekton.dev/golang-test created

$ tkn hub get task golang-build --version 0.1 |  kubectl apply -f -
task.tekton.dev/golang-build created
--

Then create the TaskRuns to execute the Tasks.

.Run the Tests
[source,shell]
--
# Run the tests and see the output with Elastic Observability
$ cat <<EOF | kubectl apply -f -
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test-my-code
spec:
  taskRef:
    name: golang-test
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: go-source
  params:
  - name: package
    value: github.com/elastic/go-licenser
  - name: packages
    value: ./...
  - name: flags
    value: -timeout 10s -p 4 -race -cover
EOF
taskrun.tekton.dev/test-my-code created
--

.Build the project
[source,shell]
--
# build
$ cat <<EOF | kubectl apply -f -
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-my-code
spec:
  taskRef:
    name: golang-build
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: go-source
  params:
  - name: package
    value: github.com/elastic/go-licenser
  - name: packages
    value: .
  - name: flags
    value: -o bin/go-licenser -ldflags="-X main.version=master-dev"
EOF
taskrun.tekton.dev/clone-my-code created
--


https://localhost:5601/app/metrics


== Tekton Metrics

Tekton Pipelines provides metrics out-of-the-box as explained on the doc at:

- https://github.com/tektoncd/pipeline/blob/v0.18.1/docs/metrics.md

.Configure access to the metrics
[source,shell]
--
$ kubectl port-forward deployment/tekton-pipelines-controller 9090 --namespace tekton-pipelines
Forwarding from 127.0.0.1:9090 -> 9090
Forwarding from [::1]:9090 -> 9090
Handling connection for 9090
Handling connection for 9090
--

.Output example
[source,shell]
--
curl http://localhost:9090/metrics
# HELP tekton_reconcile_count Number of reconcile operations
# TYPE tekton_reconcile_count counter
tekton_reconcile_count{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false"} 2
tekton_reconcile_count{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true"} 9
# HELP tekton_reconcile_latency Latency of reconcile operations
# TYPE tekton_reconcile_latency histogram
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false",le="10"} 0
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false",le="100"} 1
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false",le="1000"} 2
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false",le="10000"} 2
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false",le="30000"} 2
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false",le="60000"} 2
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false",le="+Inf"} 2
tekton_reconcile_latency_sum{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false"} 274
tekton_reconcile_latency_count{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false"} 2
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true",le="10"} 4
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true",le="100"} 9
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true",le="1000"} 9
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true",le="10000"} 9
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true",le="30000"} 9
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true",le="60000"} 9
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true",le="+Inf"} 9
tekton_reconcile_latency_sum{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true"} 187
tekton_reconcile_latency_count{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true"} 9
# HELP tekton_running_taskruns_count Number of taskruns executing currently
# TYPE tekton_running_taskruns_count gauge
tekton_running_taskruns_count 0
# HELP tekton_taskrun_count number of taskruns
# TYPE tekton_taskrun_count counter
tekton_taskrun_count{status="success"} 1
# HELP tekton_taskrun_duration_seconds The taskrun's execution time in seconds
# TYPE tekton_taskrun_duration_seconds histogram
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="10"} 0
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="30"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="60"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="300"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="900"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="1800"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="3600"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="5400"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="10800"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="21600"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="43200"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="86400"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="+Inf"} 1
tekton_taskrun_duration_seconds_sum{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run"} 13
tekton_taskrun_duration_seconds_count{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run"} 1
# HELP tekton_taskruns_pod_latency scheduling latency for the taskruns pods
# TYPE tekton_taskruns_pod_latency gauge
tekton_taskruns_pod_latency{namespace="tutorials",pod="echo-hello-world-task-run-pod-5xqd7",task="echo-hello-world",taskrun="echo-hello-world-task-run"} 0
# HELP tekton_work_queue_depth Depth of the work queue
# TYPE tekton_work_queue_depth gauge
tekton_work_queue_depth{reconciler="TaskRun"} 0
```

## Utils

Check the API Resources

```
kubectl api-resources | grep tekton.dev
clustertasks                                   tekton.dev                     false        ClusterTask
conditions                                     tekton.dev                     true         Condition
pipelineresources                              tekton.dev                     true         PipelineResource
pipelineruns                      pr,prs       tekton.dev                     true         PipelineRun
pipelines                                      tekton.dev                     true         Pipeline
taskruns                          tr,trs       tekton.dev                     true         TaskRun
tasks                                          tekton.dev                     true         Task
--

