= Tekton Pipelines and the Elastic Stack
:imagesdir: ./images

In a few minutes, you will have the following components up and running in your local Kubernetes cluster:

* Tekton https://github.com/tektoncd/pipeline/releases/tag/v0.18.1[**v0.18.1**] in the `tekton-pipelines` namespace
* Elastic Stack **7.10.0**, Elasticsearch / Kibana / Beats (filebeat and metricbeat) deployed using https://github.com/elastic/cloud-on-k8s[Elastic Cloud on Kubernetes (ECK)] in the `elastic-system` namespace


== Prerequisites

* Local Kubernetes environment (Docker for Desktop, Minikube...)  

_NOTE: for now this tutorial is only tested on Docker Desktop for Mac_


== Set up Tekton Pipelines and CLI

.Install Tekton Pipelines CRD
[source,shell]
--
# make sure you are using the right k8s context
$ kubectl config current-context
docker-for-desktop

# install Tekton Pipelines
$ kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.18.1/release.yaml

# Wait until all Tekton pods are ready
$ kubectl get pods -w -n tekton-pipelines
NAME                                           READY   STATUS    RESTARTS   AGE
tekton-pipelines-controller-77f74f5bcf-rbj8s   1/1     Running   0          1m
tekton-pipelines-webhook-f76c97965-5xkxq       1/1     Running   0          1m
--

.Install Tekton CLI

Find the best way to install it based on your local system by loogin at the official documentation:

.Homebrew example
```bash
brew install tektoncd-cli
```

.Check the versions
```bash
$ tkn version
Client version: 0.14.0
Pipeline version: v0.18.1

```

== Run your first Task

.Install Tekton task from catalog
```bash
# Install git clone Task from Tekton 
$ tkn hub get task git-clone --version 0.2 |  kubectl apply -f -
task.tekton.dev/git-clone created
```

.Trigger Task and check logs
```bash
# Create a pv to share data between task
$ cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-es-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
EOF

# Clone repo
$ cat <<EOF | kubectl apply -f -
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: clone-my-code
spec:
  taskRef:
    name: git-clone
  workspaces:
  - name: output
    persistentVolumeClaim:
      claimName: go-es-source-pvc
  params:
  - name: url
    value: https://github.com/elastic/go-elasticsearch.git
  - name: revision
    value: v7.10.0
EOF

$ tkn tr logs clone-my-code -f
[clone] + CHECKOUT_DIR=/workspace/output/
[clone] + '[[' true '==' true ]]
[clone] + cleandir
[clone] + '[[' -d /workspace/output/ ]]
[clone] + rm -rf '/workspace/output//*'
[clone] + rm -rf /workspace/output//.git
[clone] + rm -rf '/workspace/output//..?*'
[clone] + test -z
[clone] + test -z
[clone] + test -z
[clone] + /ko-app/git-init -url https://github.com/tektoncd/pipeline.git -revision master -refspec  -path /workspace/output/ '-sslVerify=true' '-submodules=true' -depth 1
[clone] {"level":"info","ts":1607383543.1383886,"caller":"git/git.go:165","msg":"Successfully cloned https://github.com/tektoncd/pipeline.git @ 2ba62c8cfc98b74a6d02e692ce181add8b2184cd (grafted, HEAD, origin/master) in path /workspace/output/"}
[clone] {"level":"info","ts":1607383543.1675713,"caller":"git/git.go:203","msg":"Successfully initialized and updated submodules in path /workspace/output/"}
[clone] + cd /workspace/output/
[clone] + git rev-parse HEAD
[clone] + RESULT_SHA=2ba62c8cfc98b74a6d02e692ce181add8b2184cd
[clone] + EXIT_CODE=0
[clone] + '[' 0 '!=' 0 ]
[clone] + echo -n 2ba62c8cfc98b74a6d02e692ce181add8b2184cd
[clone] + echo -n https://github.com/tektoncd/pipeline.git

$ tkn tr list
NAME            STARTED          DURATION     STATUS
clone-my-code   25 seconds ago   16 seconds   Succeeded

```

What about using Elastic Observalibily to access these logs and metrics?

== Set up Elastic Stack with ECK

.Install ECK
```bash
$ kubectl apply -f https://download.elastic.co/downloads/eck/1.3.0/all-in-one.yaml
```

.Install Elasticsearch, Kibana and Beats
```bash
$ kubectl apply -n elastic-system -f https://raw.githubusercontent.com/mgreau/tekton-pipelines-elastic-tutorials/master/config/eck/monitoring-es-kb.yaml

$ kubectl apply -n elastic-system -f https://raw.githubusercontent.com/mgreau/tekton-pipelines-elastic-tutorials/master/config/eck/monitoring-filebeat-metricbeat.yaml
```

When the set-up is done, you should have a *Kibana pod up and running*:

[source,shell]
--
# Check Elastic pods
$ kubectl get pods -n elastic-system 
NAME                                 READY     STATUS    RESTARTS   AGE
elasticsearch-7bf6cd96cd-r6llt       1/1       Running   0          4m
filebeat-5lrwg                       1/1       Running   0          4m
kibana-694998774-dxwgm               1/1       Running   0          4m
kube-state-metrics-b8845b4d7-ch9v7   1/1       Running   0          4m
metricbeat-zctb6                     1/1       Running   0          4m
--

Get `elastic` user password
[source,shell]
--
echo $(kubectl get secret elasticsearch-monitoring-es-elastic-user -o=jsonpath='{.data.elastic}' | base64 --decode)
kubectl port-forward svc/kibana-monitoring-kb-http 5601
--

Access
```
open https://localhost:5601/app/observability/overview
```


== Monitor Build using Elastic Observablity


.Install Tekton task from catalog
```bash
# Install golang-build Task from catalog 
$ tkn hub get task golang-build --version 0.1 |  kubectl apply -f -
task.tekton.dev/golang-build created

# Build project and monitor with Elastic
$ cat <<EOF | kubectl apply -f -
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-my-es-code
spec:
  taskRef:
    name: golang-build
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: go-es-source-pvc
  params:
  - name: package
    value: github.com/elastic/go-elasticsearch/...
  - name: packages
    value: github.com/elastic/go-elasticsearch/...
EOF
```


https://localhost:5601/app/metrics


=== Tekton Metrics

To check the Tekton metrics

```
kubectl port-forward deployment/tekton-pipelines-controller 9090 --namespace tekton-pipelines
Forwarding from 127.0.0.1:9090 -> 9090
Forwarding from [::1]:9090 -> 9090
Handling connection for 9090
Handling connection for 9090
```

and then
```
curl http://localhost:9090/metrics
# HELP tekton_reconcile_count Number of reconcile operations
# TYPE tekton_reconcile_count counter
tekton_reconcile_count{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false"} 2
tekton_reconcile_count{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true"} 9
# HELP tekton_reconcile_latency Latency of reconcile operations
# TYPE tekton_reconcile_latency histogram
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false",le="10"} 0
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false",le="100"} 1
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false",le="1000"} 2
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false",le="10000"} 2
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false",le="30000"} 2
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false",le="60000"} 2
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false",le="+Inf"} 2
tekton_reconcile_latency_sum{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false"} 274
tekton_reconcile_latency_count{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="false"} 2
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true",le="10"} 4
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true",le="100"} 9
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true",le="1000"} 9
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true",le="10000"} 9
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true",le="30000"} 9
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true",le="60000"} 9
tekton_reconcile_latency_bucket{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true",le="+Inf"} 9
tekton_reconcile_latency_sum{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true"} 187
tekton_reconcile_latency_count{key="tutorials/echo-hello-world-task-run",reconciler="TaskRun",success="true"} 9
# HELP tekton_running_taskruns_count Number of taskruns executing currently
# TYPE tekton_running_taskruns_count gauge
tekton_running_taskruns_count 0
# HELP tekton_taskrun_count number of taskruns
# TYPE tekton_taskrun_count counter
tekton_taskrun_count{status="success"} 1
# HELP tekton_taskrun_duration_seconds The taskrun's execution time in seconds
# TYPE tekton_taskrun_duration_seconds histogram
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="10"} 0
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="30"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="60"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="300"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="900"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="1800"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="3600"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="5400"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="10800"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="21600"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="43200"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="86400"} 1
tekton_taskrun_duration_seconds_bucket{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run",le="+Inf"} 1
tekton_taskrun_duration_seconds_sum{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run"} 13
tekton_taskrun_duration_seconds_count{namespace="tutorials",status="success",task="echo-hello-world",taskrun="echo-hello-world-task-run"} 1
# HELP tekton_taskruns_pod_latency scheduling latency for the taskruns pods
# TYPE tekton_taskruns_pod_latency gauge
tekton_taskruns_pod_latency{namespace="tutorials",pod="echo-hello-world-task-run-pod-5xqd7",task="echo-hello-world",taskrun="echo-hello-world-task-run"} 0
# HELP tekton_work_queue_depth Depth of the work queue
# TYPE tekton_work_queue_depth gauge
tekton_work_queue_depth{reconciler="TaskRun"} 0
```

## Utils

Check the API Resources

```
kubectl api-resources | grep tekton.dev
clustertasks                                   tekton.dev                     false        ClusterTask
conditions                                     tekton.dev                     true         Condition
pipelineresources                              tekton.dev                     true         PipelineResource
pipelineruns                      pr,prs       tekton.dev                     true         PipelineRun
pipelines                                      tekton.dev                     true         Pipeline
taskruns                          tr,trs       tekton.dev                     true         TaskRun
tasks                                          tekton.dev                     true         Task
```

