# Tasks related to Docker work
apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: kaniko-push
  namespace: kaniko-tutorial
spec:
  inputs:
    resources:
      - name: workspace
        type: git
    params:
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/workspace/Dockerfile
  outputs:
    resources:
      - name: builtImage
        type: image
  volumes:
    - name: docker-cfg
      secret:
        secretName: kaniko-secret
        items:
          - key: config.json
            path: config.json
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:debug
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --context=dir://workspace/workspace"
        - --destination=${outputs.resources.builtImage.url}
      volumeMounts:
        - name: docker-cfg
          mountPath: /kaniko/.docker/
---
