apiVersion: pipeline.knative.dev/v1alpha1
kind: TaskRun
metadata:
  name: kaniko-pushrun
  namespace: kaniko-tutorial
spec:
  taskRef:
    name: kaniko-push
  trigger:
      type: manual
  inputs:
    resources:
    - name: workspace
      resourceRef:
        name: git-kaniko-helloworld
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: image-kaniko-helloworld
