apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-kaniko-helloworld
  namespace: tutorials
spec:
  type: git
  params:
  - name: url
    value: https://github.com/mgreau/knative-tutorial-resources.git
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-and-push
  namespace: tutorials
spec:
  taskRef:
    name: kaniko
  trigger:
      type: manual
  inputs:
    resources:
    - name: workspace
      resourceRef:
        name: git-kaniko-helloworld
    params:
      - name: pathToDockerFile
        value: /workspace/workspace/Dockerfile.gradle
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: image-kaniko-helloworld
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image-kaniko-helloworld
  namespace: tutorials
spec:
  type: image
  params:
    - name: url
      value: {{DOCKER_HUB_USERNAME}}/kaniko-hello